package corpus

import (
	"strings"
	"testing"
)

func TestDocNodeBecomesAFileNamedAfterItsTitle(t *testing.T) {
	r := Render("d6dd5b65::domain", []Entry{{
		ID:        "doc-1",
		EntryType: "decision.made",
		Content:   "DOC-NODE · THE METHODOLOGY v4.1 (page 3801315) — the planning and process stack.",
	}})

	if len(r.Files) != 1 {
		t.Fatalf("want 1 file, got %d", len(r.Files))
	}
	if r.Files[0].Name != "the-methodology.md" {
		t.Errorf("want the-methodology.md, got %q", r.Files[0].Name)
	}
	if r.Files[0].Title != "THE METHODOLOGY v4.1" {
		t.Errorf("want title THE METHODOLOGY v4.1, got %q", r.Files[0].Title)
	}
}

func TestAnEntryWhoseCausationChainReachesADocNodeIsASectionOfThatDocument(t *testing.T) {
	r := Render("d6dd5b65::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "kf", CausationID: "doc-1", EntryType: "keyframe.written", Content: "navigation"},
		{ID: "sec", CausationID: "kf", EntryType: "decision.made", Content: "METHODOLOGY §1a · CORE THESIS. Thesis: precision or halt."},
	})

	if len(r.Files) != 1 {
		t.Fatalf("want 1 file, got %d", len(r.Files))
	}
	if !strings.Contains(r.Files[0].Markdown, "CORE THESIS") {
		t.Errorf("section reached through a keyframe is missing:\n%s", r.Files[0].Markdown)
	}
}

func TestASectionsHeadingIsItsFirstSentenceAndItsBodyTheRest(t *testing.T) {
	r := Render("d6dd5b65::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "sec", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §1a · CORE THESIS. Thesis: precision or halt. Corollary: never proceed plausibly."},
	})

	for _, want := range []string{"## METHODOLOGY §1a · CORE THESIS\n", "\nThesis: precision or halt. Corollary: never proceed plausibly.\n"} {
		if !strings.Contains(r.Files[0].Markdown, want) {
			t.Errorf("want %q in\n%q", want, r.Files[0].Markdown)
		}
	}
}

func TestEverySectionIsStampedWithTheEntryItCameFrom(t *testing.T) {
	r := Render("d6dd5b65::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "1768ca87", CausationID: "doc-1", EntryType: "decision.made", Timestamp: "2026-08-05T19:56:10.188Z", Content: "METHODOLOGY §1a · CORE THESIS. Thesis: precision or halt."},
	})

	want := "## METHODOLOGY §1a · CORE THESIS\n`1768ca87` · 2026-08-05T19:56:10.188Z\n\nThesis: precision or halt.\n"
	if !strings.Contains(r.Files[0].Markdown, want) {
		t.Errorf("want\n%q\ngot\n%q", want, r.Files[0].Markdown)
	}
}

func TestADocumentOpensWithItsTitleAndSaysWhatGeneratedIt(t *testing.T) {
	r := Render("d6dd5b65::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the planning and process stack."},
	})

	md := r.Files[0].Markdown
	for _, want := range []string{
		"# THE METHODOLOGY v4.1\n",
		"GENERATED by `flmnt corpus` from `d6dd5b65::domain`, DOC-NODE `doc-1`",
		"Do not edit",
		"\nthe planning and process stack.\n",
	} {
		if !strings.Contains(md, want) {
			t.Errorf("want %q in\n%s", want, md)
		}
	}
}

func TestASupersededSectionRendersItsSupersedersContentInItsOwnPosition(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "old", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §1a · GENERATED TESTS ARE COMMITTED. Commit the compiled suite."},
		{ID: "z-end", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §9z · CLOSING. Last section."},
		{ID: "new", CausationID: "old", EntryType: "decision.superseded", Content: "METHODOLOGY §1a · GENERATED TESTS ARE NEVER COMMITTED. CI compiles every run."},
	})

	md := r.Files[0].Markdown
	if strings.Contains(md, "\n## METHODOLOGY §1a · GENERATED TESTS ARE COMMITTED\n") {
		t.Errorf("superseded heading still presented as current:\n%s", md)
	}
	if !strings.Contains(md, "## METHODOLOGY §1a · GENERATED TESTS ARE NEVER COMMITTED\n`new`") {
		t.Errorf("superseder missing:\n%s", md)
	}
	if strings.Index(md, "NEVER COMMITTED") > strings.Index(md, "§9z") {
		t.Errorf("superseder rendered after §9z instead of in §1a's position:\n%s", md)
	}
}

func TestTheReplacedTextSurvivesInAnAppendixNamingItsSuperseder(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "old", CausationID: "doc-1", EntryType: "decision.made", Timestamp: "2026-08-05T00:00:00Z", Content: "METHODOLOGY §1a · TESTS ARE COMMITTED. Commit the compiled suite."},
		{ID: "new", CausationID: "old", EntryType: "decision.superseded", Content: "METHODOLOGY §1a · TESTS ARE NEVER COMMITTED. CI compiles every run."},
	})

	md := r.Files[0].Markdown
	for _, want := range []string{
		"## Superseded\n",
		"`old` · 2026-08-05T00:00:00Z — replaced by `new`",
		"Commit the compiled suite.",
	} {
		if !strings.Contains(md, want) {
			t.Errorf("want %q in\n%s", want, md)
		}
	}
}

func TestASupersessionChainRendersOnlyItsFinalRulingAsCurrent(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "v1", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §1a · FIRST. one."},
		{ID: "v2", CausationID: "v1", EntryType: "decision.superseded", Content: "METHODOLOGY §1a · SECOND. two."},
		{ID: "v3", CausationID: "v2", EntryType: "decision.superseded", Content: "METHODOLOGY §1a · THIRD. three."},
	})

	md := r.Files[0].Markdown
	if !strings.Contains(md, "\n## METHODOLOGY §1a · THIRD\n") {
		t.Errorf("last ruling in the chain is not the current section:\n%s", md)
	}
	for _, stale := range []string{"\n## METHODOLOGY §1a · FIRST\n", "\n## METHODOLOGY §1a · SECOND\n"} {
		if strings.Contains(md, stale) {
			t.Errorf("%q is still presented as current:\n%s", stale, md)
		}
	}
}

func TestADoctrineDecisionThatReachesNoDocNodeStillRenders(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "ruling", EntryType: "decision.made", Timestamp: "2026-09-28T00:00:00Z", Content: "FOUNDER RULING (2026-09-28). Workspace isolation is provided by access permissions."},
	})

	if len(r.Files) != 2 {
		t.Fatalf("want a rulings file beside the document, got %d files", len(r.Files))
	}
	if r.Files[1].Name != "rulings.md" {
		t.Errorf("want rulings.md, got %q", r.Files[1].Name)
	}
	if !strings.Contains(r.Files[1].Markdown, "## FOUNDER RULING (2026-09-28)\n`ruling`") {
		t.Errorf("unassigned ruling missing:\n%s", r.Files[1].Markdown)
	}
}

func TestEntriesThatAreNotDoctrineRenderNowhereAndAreCounted(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "kf", CausationID: "doc-1", EntryType: "keyframe.written", Content: "NAVIGATION. index of every entry id."},
		{ID: "ex", CausationID: "doc-1", EntryType: "exploration.committed", Content: "SEEDING PROBE. verifying the write path."},
	})

	if strings.Contains(r.Files[0].Markdown, "NAVIGATION") || strings.Contains(r.Files[0].Markdown, "SEEDING PROBE") {
		t.Errorf("a keyframe or exploration was rendered as doctrine:\n%s", r.Files[0].Markdown)
	}
	want := map[string]int{"keyframe.written": 1, "exploration.committed": 1}
	for kind, n := range want {
		if r.Unrendered[kind] != n {
			t.Errorf("want %d %s counted, got %d", n, kind, r.Unrendered[kind])
		}
	}
}
