package corpus

import (
	"strings"
	"testing"
)

func TestDocNodeBecomesAFileNamedAfterItsTitle(t *testing.T) {
	r := Render("d6dd5b65::domain", []Entry{{
		ID:        "doc-1",
		EntryType: "decision.made",
		Content:   "DOC-NODE · THE METHODOLOGY v4.1 (page 3801315) — the planning and process stack.",
	}})

	if len(r.Files) != 1 {
		t.Fatalf("want 1 file, got %d", len(r.Files))
	}
	if r.Files[0].Name != "the-methodology.md" {
		t.Errorf("want the-methodology.md, got %q", r.Files[0].Name)
	}
	if r.Files[0].Title != "THE METHODOLOGY v4.1" {
		t.Errorf("want title THE METHODOLOGY v4.1, got %q", r.Files[0].Title)
	}
}

func TestAnEntryWhoseCausationChainReachesADocNodeIsASectionOfThatDocument(t *testing.T) {
	r := Render("d6dd5b65::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "kf", CausationID: "doc-1", EntryType: "keyframe.written", Content: "navigation"},
		{ID: "sec", CausationID: "kf", EntryType: "decision.made", Content: "METHODOLOGY §1a · CORE THESIS. Thesis: precision or halt."},
	})

	if len(r.Files) != 1 {
		t.Fatalf("want 1 file, got %d", len(r.Files))
	}
	if !strings.Contains(r.Files[0].Markdown, "CORE THESIS") {
		t.Errorf("section reached through a keyframe is missing:\n%s", r.Files[0].Markdown)
	}
}

func TestASectionsHeadingIsItsFirstSentenceAndItsBodyTheRest(t *testing.T) {
	r := Render("d6dd5b65::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "sec", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §1a · CORE THESIS. Thesis: precision or halt. Corollary: never proceed plausibly."},
	})

	for _, want := range []string{"## METHODOLOGY §1a · CORE THESIS\n", "\nThesis: precision or halt. Corollary: never proceed plausibly.\n"} {
		if !strings.Contains(r.Files[0].Markdown, want) {
			t.Errorf("want %q in\n%q", want, r.Files[0].Markdown)
		}
	}
}

func TestEverySectionIsStampedWithTheEntryItCameFrom(t *testing.T) {
	r := Render("d6dd5b65::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "1768ca87", CausationID: "doc-1", EntryType: "decision.made", Timestamp: "2026-08-05T19:56:10.188Z", Content: "METHODOLOGY §1a · CORE THESIS. Thesis: precision or halt."},
	})

	want := "## METHODOLOGY §1a · CORE THESIS\n`1768ca87` · 2026-08-05T19:56:10.188Z\n\nThesis: precision or halt.\n"
	if !strings.Contains(r.Files[0].Markdown, want) {
		t.Errorf("want\n%q\ngot\n%q", want, r.Files[0].Markdown)
	}
}

func TestADocumentOpensWithItsTitleAndSaysWhatGeneratedIt(t *testing.T) {
	r := Render("d6dd5b65::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the planning and process stack."},
	})

	md := r.Files[0].Markdown
	for _, want := range []string{
		"# THE METHODOLOGY v4.1\n",
		"GENERATED by `flmnt corpus` from `d6dd5b65::domain`, DOC-NODE `doc-1`",
		"Do not edit",
		"\nthe planning and process stack.\n",
	} {
		if !strings.Contains(md, want) {
			t.Errorf("want %q in\n%s", want, md)
		}
	}
}

func TestASupersededSectionRendersItsSupersedersContentInItsOwnPosition(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "old", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §1a · GENERATED TESTS ARE COMMITTED. Commit the compiled suite."},
		{ID: "z-end", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §9z · CLOSING. Last section."},
		{ID: "new", CausationID: "old", EntryType: "decision.superseded", Content: "METHODOLOGY §1a · GENERATED TESTS ARE NEVER COMMITTED. CI compiles every run."},
	})

	md := r.Files[0].Markdown
	if strings.Contains(md, "\n## METHODOLOGY §1a · GENERATED TESTS ARE COMMITTED\n") {
		t.Errorf("superseded heading still presented as current:\n%s", md)
	}
	if !strings.Contains(md, "## METHODOLOGY §1a · GENERATED TESTS ARE NEVER COMMITTED\n`new`") {
		t.Errorf("superseder missing:\n%s", md)
	}
	if strings.Index(md, "NEVER COMMITTED") > strings.Index(md, "§9z") {
		t.Errorf("superseder rendered after §9z instead of in §1a's position:\n%s", md)
	}
}

func TestTheReplacedTextSurvivesInAnAppendixNamingItsSuperseder(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "old", CausationID: "doc-1", EntryType: "decision.made", Timestamp: "2026-08-05T00:00:00Z", Content: "METHODOLOGY §1a · TESTS ARE COMMITTED. Commit the compiled suite."},
		{ID: "new", CausationID: "old", EntryType: "decision.superseded", Content: "METHODOLOGY §1a · TESTS ARE NEVER COMMITTED. CI compiles every run."},
	})

	md := r.Files[0].Markdown
	for _, want := range []string{
		"## Superseded\n",
		"`old` · 2026-08-05T00:00:00Z — replaced by `new`",
		"Commit the compiled suite.",
	} {
		if !strings.Contains(md, want) {
			t.Errorf("want %q in\n%s", want, md)
		}
	}
}

func TestASupersessionChainRendersOnlyItsFinalRulingAsCurrent(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "v1", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §1a · FIRST. one."},
		{ID: "v2", CausationID: "v1", EntryType: "decision.superseded", Content: "METHODOLOGY §1a · SECOND. two."},
		{ID: "v3", CausationID: "v2", EntryType: "decision.superseded", Content: "METHODOLOGY §1a · THIRD. three."},
	})

	md := r.Files[0].Markdown
	if !strings.Contains(md, "\n## METHODOLOGY §1a · THIRD\n") {
		t.Errorf("last ruling in the chain is not the current section:\n%s", md)
	}
	for _, stale := range []string{"\n## METHODOLOGY §1a · FIRST\n", "\n## METHODOLOGY §1a · SECOND\n"} {
		if strings.Contains(md, stale) {
			t.Errorf("%q is still presented as current:\n%s", stale, md)
		}
	}
}

func TestADoctrineDecisionThatReachesNoDocNodeStillRenders(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "ruling", EntryType: "decision.made", Timestamp: "2026-09-28T00:00:00Z", Content: "FOUNDER RULING (2026-09-28). Workspace isolation is provided by access permissions."},
	})

	if len(r.Files) != 2 {
		t.Fatalf("want a rulings file beside the document, got %d files", len(r.Files))
	}
	if r.Files[1].Name != "rulings.md" {
		t.Errorf("want rulings.md, got %q", r.Files[1].Name)
	}
	if !strings.Contains(r.Files[1].Markdown, "## FOUNDER RULING (2026-09-28)\n`ruling`") {
		t.Errorf("unassigned ruling missing:\n%s", r.Files[1].Markdown)
	}
}

func TestEntriesThatAreNotDoctrineRenderNowhereAndAreCounted(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "kf", CausationID: "doc-1", EntryType: "keyframe.written", Content: "NAVIGATION. index of every entry id."},
		{ID: "ex", CausationID: "doc-1", EntryType: "exploration.committed", Content: "SEEDING PROBE. verifying the write path."},
	})

	if strings.Contains(r.Files[0].Markdown, "NAVIGATION") || strings.Contains(r.Files[0].Markdown, "SEEDING PROBE") {
		t.Errorf("a keyframe or exploration was rendered as doctrine:\n%s", r.Files[0].Markdown)
	}
	want := map[string]int{"keyframe.written": 1, "exploration.committed": 1}
	for kind, n := range want {
		if r.Unrendered[kind] != n {
			t.Errorf("want %d %s counted, got %d", n, kind, r.Unrendered[kind])
		}
	}
}

func TestADocumentRecordsHowManySectionsItRendered(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "a", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §1a · ONE. one."},
		{ID: "b", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §1b · TWO. two."},
		{ID: "c", CausationID: "b", EntryType: "decision.superseded", Content: "METHODOLOGY §1b · TWO, REVISED. still two."},
	})

	if r.Files[0].Sections != 2 {
		t.Errorf("want 2 sections (a superseder replaces a section, it does not add one), got %d", r.Files[0].Sections)
	}
}

func TestTwoRulingsThatAmendTheSameSectionBothRender(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "orig", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §5c · A/B/C/D. the subtask pattern."},
		{ID: "amend-a", CausationID: "orig", EntryType: "decision.superseded", Content: "METHODOLOGY §5c AMENDED · A/B/C/D RETIRED. no subtasks."},
		{ID: "amend-b", CausationID: "orig", EntryType: "decision.superseded", Content: "METHODOLOGY §5c · B-STEP CORRECTION. tests are never committed."},
	})

	md := r.Files[0].Markdown
	for _, want := range []string{"\n## METHODOLOGY §5c AMENDED · A/B/C/D RETIRED\n", "\n## METHODOLOGY §5c · B-STEP CORRECTION\n"} {
		if !strings.Contains(md, want) {
			t.Errorf("an amendment to the same section was dropped — want %q in\n%s", want, md)
		}
	}
	if !strings.Contains(md, "replaced by `amend-a`, `amend-b`") {
		t.Errorf("the appendix must name every ruling that replaced the original:\n%s", md)
	}
}

func TestASupersessionOfSomethingThatIsNotDoctrineStillRenders(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "kf", CausationID: "doc-1", EntryType: "keyframe.written", Content: "HARVEST WRITE PATH UNDER WAY. state, not doctrine."},
		{ID: "ruling", CausationID: "kf", EntryType: "decision.superseded", Content: "HARVEST IS FOUNDER-AUTHORISED. proceed."},
	})

	if !strings.Contains(r.Files[0].Markdown, "\n## HARVEST IS FOUNDER-AUTHORISED\n") {
		t.Errorf("a supersession whose target is a keyframe was dropped:\n%s", r.Files[0].Markdown)
	}
	if r.Files[0].Sections != 1 {
		t.Errorf("want it counted as a section, got %d", r.Files[0].Sections)
	}
}

func TestEveryDoctrineEntryRendersExactlyOnce(t *testing.T) {
	entries := []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "a", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §1 · ONE. one."},
		{ID: "b", CausationID: "a", EntryType: "decision.superseded", Content: "METHODOLOGY §1 · ONE REVISED. one again."},
		{ID: "c", CausationID: "a", EntryType: "decision.superseded", Content: "METHODOLOGY §1 · ONE AMENDED. one also."},
		{ID: "d", CausationID: "b", EntryType: "decision.superseded", Content: "METHODOLOGY §1 · ONE FINAL. one at last."},
		{ID: "kf", CausationID: "doc-1", EntryType: "keyframe.written", Content: "NAVIGATION. state."},
		{ID: "e", CausationID: "kf", EntryType: "decision.superseded", Content: "RULING ON STATE. doctrine anyway."},
		{ID: "f", EntryType: "decision.made", Content: "FOUNDER RULING. unwired."},
	}

	r := Render("s::domain", entries)

	doctrine := 0
	for _, e := range entries {
		if strings.HasPrefix(e.Content, "DOC-NODE") {
			continue
		}
		if e.EntryType == "decision.made" || e.EntryType == "decision.superseded" {
			doctrine++
		}
	}
	rendered, retiredCount := 0, 0
	for _, f := range r.Files {
		rendered += f.Sections
		retiredCount += strings.Count(f.Markdown, "— replaced by ")
	}
	if rendered+retiredCount != doctrine {
		t.Errorf("%d doctrine entries but %d sections + %d retired — the render loses or duplicates entries", doctrine, rendered, retiredCount)
	}
}

func TestASectionEndsWithABlankLineSoTheNextHeadingIsNotCrowded(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "a", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §1 · ONE. one."},
		{ID: "b", CausationID: "doc-1", EntryType: "decision.made", Content: "METHODOLOGY §2 · TWO. two."},
	})

	if !strings.Contains(r.Files[0].Markdown, "one.\n\n## METHODOLOGY §2") {
		t.Errorf("a section must be separated from the next heading:\n%s", r.Files[0].Markdown)
	}
}

func TestAStreamWithNoDocNodeRendersNothing(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "a", EntryType: "decision.made", Content: "USE POSTGRES. for persistence."},
		{ID: "b", EntryType: "decision.made", Content: "SHARD BY TENANT. one schema each."},
	})

	if len(r.Files) != 0 {
		t.Errorf("a stream with no DOC-NODE is not a doctrine corpus — rulings.md supplements one, it does not stand in for one; got %d files", len(r.Files))
	}
}

func TestTheHeaderRecordsTheNewestEntryItRenderedFrom(t *testing.T) {
	r := Render("s::domain", []Entry{
		{ID: "doc-1", EntryType: "decision.made", Timestamp: "2026-08-05T19:56:10.188Z", Content: "DOC-NODE · THE METHODOLOGY v4.1 (page 1) — the stack."},
		{ID: "old", CausationID: "doc-1", EntryType: "decision.made", Timestamp: "2026-08-06T00:00:00.000Z", Content: "METHODOLOGY §1 · ONE. one."},
		{ID: "4d8a6f15", CausationID: "doc-1", EntryType: "decision.made", Timestamp: "2026-09-28T23:16:56.005Z", Content: "METHODOLOGY §2 · TWO. two."},
	})

	// Scoped to the HEADER — everything before the first section. The same timestamp and id appear in
	// that entry's own section stamp, so an unscoped search would pass without a header at all.
	md := r.Files[0].Markdown
	header := md
	if i := strings.Index(md, "\n## "); i >= 0 {
		header = md[:i]
	}
	for _, want := range []string{"2026-09-28T23:16:56.005Z", "`4d8a6f15`", "3 entries"} {
		if !strings.Contains(header, want) {
			t.Errorf("a reader must be able to judge how current this is — want %q in the header\n%s", want, header)
		}
	}
}
