// Package corpus renders a flmnt doctrine stream to markdown. The structure is derived, never
// declared: a DOC-NODE entry is a document, the entries whose causation chain reaches it are its
// sections, and a `decision.superseded` entry replaces the entry its causationId names. Nothing
// here is hand-maintained, so a doctrine ruling recorded in flmnt cannot drift from the markdown.
package corpus

import (
	"regexp"
	"strings"
)

// Entry is one event in a stream, as memorySlice returns it.
type Entry struct {
	ID          string
	CausationID string
	EntryType   string
	Timestamp   string
	Content     string
}

// File is one rendered document.
type File struct {
	Name     string
	Title    string
	Markdown string
}

// Report is everything a render produced.
type Report struct {
	Files []File
}

const (
	docNodePrefix  = "DOC-NODE · "
	decisionType   = "decision.made"
	rulingsOwner   = ""
	rulingsTitle   = "Rulings recorded outside the document tree"
	supersededType = "decision.superseded"
)

var (
	trailingVersion = regexp.MustCompile(`\s+v\d+(\.\d+)*$`)
	nonSlug         = regexp.MustCompile(`[^a-z0-9]+`)
)

// Render turns a stream slice into documents.
func Render(streamID string, entries []Entry) Report {
	byID := make(map[string]Entry, len(entries))
	docs := make(map[string]bool)
	replacedBy := make(map[string]string)
	for _, e := range entries {
		byID[e.ID] = e
		if strings.HasPrefix(e.Content, docNodePrefix) {
			docs[e.ID] = true
		}
		if e.EntryType == supersededType {
			replacedBy[e.CausationID] = e.ID
		}
	}

	var r Report
	fileOf := make(map[string]int)
	bodies := make(map[string]*strings.Builder)
	replaced := make(map[string]*strings.Builder)
	for _, e := range entries {
		if !docs[e.ID] {
			continue
		}
		title := docTitle(e.Content)
		fileOf[e.ID] = len(r.Files)
		bodies[e.ID] = &strings.Builder{}
		replaced[e.ID] = &strings.Builder{}
		bodies[e.ID].WriteString(header(streamID, e, title))
		r.Files = append(r.Files, File{Name: slug(title) + ".md", Title: title})
	}

	for _, e := range entries {
		if docs[e.ID] || e.EntryType != decisionType {
			continue
		}
		owner := ownerDoc(e, byID, docs)
		if owner == rulingsOwner {
			if _, open := bodies[owner]; !open {
				fileOf[owner] = len(r.Files)
				bodies[owner] = &strings.Builder{}
				replaced[owner] = &strings.Builder{}
				bodies[owner].WriteString(rulingsHeader(streamID))
				r.Files = append(r.Files, File{Name: "rulings.md", Title: rulingsTitle})
			}
		}
		bodies[owner].WriteString(section(current(e, byID, replacedBy)))
		for at := e; replacedBy[at.ID] != ""; at = byID[replacedBy[at.ID]] {
			replaced[owner].WriteString(retired(at, replacedBy[at.ID]))
		}
	}
	for id, i := range fileOf {
		md := bodies[id].String()
		if past := replaced[id].String(); past != "" {
			md += "## Superseded\n\nWhat these entries said before the ruling that replaced them. Kept so a reader\nmeeting the old wording elsewhere can see it was answered, not forgotten.\n\n" + past
		}
		r.Files[i].Markdown = md
	}
	return r
}

// ownerDoc walks causationId until it lands on a DOC-NODE; "" when the chain reaches none. Visited
// ids are tracked so a self-referencing or cyclic chain terminates instead of spinning.
func ownerDoc(e Entry, byID map[string]Entry, docs map[string]bool) string {
	seen := map[string]bool{}
	for cur, ok := e, true; ok && !seen[cur.ID]; cur, ok = byID[cur.CausationID] {
		seen[cur.ID] = true
		if docs[cur.ID] {
			return cur.ID
		}
	}
	return ""
}

// rulingsHeader opens the file for doctrine that never got wired to a DOC-NODE. Dropping those
// entries would be the worst outcome available: they are the newest rulings, and the ones most
// likely to overturn what the seeded documents still say.
func rulingsHeader(streamID string) string {
	return "# " + rulingsTitle + "\n\n" +
		"> GENERATED by `flmnt corpus` from `" + streamID + "`.\n" +
		"> Do not edit: a correction made here is lost on the next render. Record it in flmnt instead.\n\n" +
		"Decisions in this stream whose causal chain reaches no DOC-NODE. They are doctrine all the\n" +
		"same — usually later rulings — so they render here rather than vanishing.\n\n"
}

// header opens a document: its title, the banner that stops anyone hand-editing it, and the DOC-NODE's
// own prose as the scope statement.
func header(streamID string, doc Entry, title string) string {
	scope := strings.TrimSpace(docScope(doc.Content))
	return "# " + title + "\n\n" +
		"> GENERATED by `flmnt corpus` from `" + streamID + "`, DOC-NODE `" + doc.ID + "`.\n" +
		"> Do not edit: a correction made here is lost on the next render. Record it in flmnt instead.\n\n" +
		scope + "\n\n"
}

// docScope is the DOC-NODE prose that follows the title — what the document owns.
func docScope(content string) string {
	rest := strings.TrimPrefix(content, docNodePrefix)
	if i := strings.Index(rest, " — "); i >= 0 {
		return rest[i+len(" — "):]
	}
	return ""
}

// current follows the supersession chain from an entry to the ruling that stands today. A superseder
// takes the position of what it replaced, so a document keeps its shape while its doctrine moves on.
func current(e Entry, byID map[string]Entry, replacedBy map[string]string) Entry {
	seen := map[string]bool{}
	for !seen[e.ID] {
		seen[e.ID] = true
		next, ok := byID[replacedBy[e.ID]]
		if !ok {
			return e
		}
		e = next
	}
	return e
}

// retired renders one replaced entry into the appendix — its own words, and the id that answered them.
func retired(e Entry, by string) string {
	return "### " + strings.TrimSpace(headingOf(e.Content)) + "\n`" + e.ID + "` · " + e.Timestamp +
		" — replaced by `" + by + "`\n\n" + bodyOf(e.Content) + "\n"
}

// section renders one entry as a markdown section: its opening sentence becomes the heading, the
// rest the body. Doctrine entries are authored as "TITLE. prose…", so the split is the author's own
// and not a guess at where a title ends. The stamp is what makes a rendered claim checkable: a reader
// who doubts a line can go read the entry it came from.
func section(e Entry) string {
	return "## " + strings.TrimSpace(headingOf(e.Content)) + "\n`" + e.ID + "` · " + e.Timestamp +
		"\n\n" + bodyOf(e.Content) + "\n"
}

func headingOf(content string) string {
	if i := strings.Index(content, ". "); i >= 0 {
		return content[:i]
	}
	return content
}

func bodyOf(content string) string {
	if i := strings.Index(content, ". "); i >= 0 {
		return strings.TrimSpace(content[i+2:])
	}
	return ""
}

// docTitle is the document's name: what follows the DOC-NODE marker, up to the page citation or the
// subtitle dash — whichever comes first.
func docTitle(content string) string {
	rest := strings.TrimPrefix(content, docNodePrefix)
	for _, cut := range []string{" (page", " — "} {
		if i := strings.Index(rest, cut); i >= 0 {
			rest = rest[:i]
		}
	}
	return strings.TrimSpace(rest)
}

// slug is the file name. A trailing version is dropped so a version bump renames no file.
func slug(title string) string {
	s := trailingVersion.ReplaceAllString(title, "")
	return strings.Trim(nonSlug.ReplaceAllString(strings.ToLower(s), "-"), "-")
}
